@echo off

set "folder=C:\Users\Evyatar Bruch\algorithm_website\src\windows"
mkdir "%folder%"

for %%i in (
    "InsertionSort"
    "DFS"
    "SelectionSort"
    "MergeSort"
    "HeapSort"
    "QuickSort"
    "BinarySort"
    "CountingSort"
    "RadixSort"
    "BucketSort"
    "LinkedList"
    "Stack"
    "Queue"
    "BST"
    "AVL"
    "Heap"
    "MaxMinHeap"
    "PriorityQueue"
    "DecisionTree"
    "HashTable"
    "Trie"
    "HofmanAlgorithm"
    "Graphs"
    "2-3Tree"
    "BTree"
    "FindTheIValue"
    "AStar"
    "IDSearch"
    "HillClimbingSearch"
    "GradientDescent"
    "Minimax"
    "CSP"
    "Regression"
    "KNN"
    "KMeans"
) do (
    set "name=%%~i"
    set "name=!name: =_!"
    echo.> "%folder%\!name!.js"
    echo.> "%folder%\!name!.css"
    echo rem JavaScript file for !name!> "%folder%\!name!.js"
    echo /* CSS file for !name! */> "%folder%\!name!.css"
)
